name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install wheel
      run: python -m pip install --upgrade wheel
    - name: Install poetry
      run: |
        pip install --user pipx
        pipx ensurepath
        pipx install poetry
    - name: Install dependencies
      run: poetry install
    - name: Run PyTest
      run: pytest .
    - name: Build
      run: poetry build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist
